my_string = input("Введите слово (предложение): ")
print(my_string.upper())
print(my_string.lower())
print(my_string .replace(" ", ""))
print(my_string[0])
print(my_string[-1])
print("Количество символов в слове (предложении): ", len(my_string))
